language: ruby
rvm:
  #- 2.2
  - 2.1
  - 2.0.0
  #- 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - ree

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ree
  exclude:
    - rvm: 2.0.0
    - rvm: 2.1
  include:
    - rvm:1.9.3
      env:
        - foo=bar
        - bar=foo
        
script: ruby check-syntax.rb

